<?php
/** @var Alevel\LoyaltyProgram\Block\AddPointsInTotal $block */
?>
<?php if ($block->isLogged()) { ?>
<div class="col-mp mp-12">
    <input id="use-points" type="checkbox" name="use_points" <?php echo $block->isChecked() ? 'checked="checked"' : ''; ?> />
    <label for="place-order-countpoints"><span>Use points</span></label>
</div>
<script>
    require(['jquery', 'Magento_Checkout/js/model/quote', 'Magento_Checkout/js/action/get-totals'], function ($, quote, getTotals) {
        $("#use-points").on('change',function() {
            let use_points_check = this;
            let url = "<?php echo $block->getUrl('loyaltyprogram/manage/points', ['_secure'=>true]) ?>";
            $.ajax({
                url: url,
                type: "POST",
                data: {"use_points":$('#use-points').prop("checked"), "quote_id": quote.getQuoteId()},
                dataType: 'json',
                showLoader: true,
                cache: false,
                success: function(response){
                    getTotals([], false);
                    if(response.errors) {
                        use_points_check.prop("checked", false);
                        console.log(response.message);
                    } else {
                        console.log(response.message);
                    }
                }
            });
        });
    });
</script>
<?php } ?>