<div class="fieldset-wrapper customer-information">
    <div class="fieldset-wrapper-title">
        <span class="title"><?php echo __('Loyalty Program Information') ?></span>
    </div>
    <table class="admin__table-secondary">
        <tbody>
        <tr>
            <th><?php echo __('Current Loyalty Points :') ?></th>
            <td><input type="text" name="loyalty_points" value="<?php echo $block->getPoints(); ?>" /></td>
        </tr>
        </tbody>
    </table>
</div>