<?php
/** @var Alevel\LoyaltyProgram\Block\AddPointsInTotal $block */
?>
<div class="col-mp mp-12">
    <input id="place-order-countpoints" type="checkbox" name="countpoints" <?php echo $block->isChecked() ? 'checked="checked"' : ''; ?> />
    <label for="place-order-countpoints"><span>Use points</span></label>
</div>
<script>
    require(['jquery'], function ($) {
        $("#place-order-countpoints").on('change',function() {
            console.log('change');
            var url = "<?php echo $block->getUrl('loyaltyprogram/manage/updatesession', array('_secure'=>true)) ?>";
            $.ajax({
                url: url,
                type: "POST",
                data: {checked:1},
                showLoader: true,
                cache: false,
                success: function(response){
                    console.log("success1");
                }
            });
        });
    });
</script>