<?php
/** @var Alevel\LoyaltyProgram\Block\Manage $block*/
?>
<?php echo 'getPoints ' . $block->getPoints(); ?><br>
<?php echo 'getSessionCustomerId ' . $block->getSessionCustomerId(); ?><br>
<?php echo 'getReferralLink ' . $block->getReferralLink(); ?><br>
<?php echo 'getCustomerId ' . $block->getCustomerId(); ?><br>
<?php echo 'getCustomers ' . $block->getCustomers(); ?><br>
<?php echo 'this loyalty'; ?>